const CORS_PROXY = "https://cors-anywhere.herokuapp.com/";
const TARGET_URL = "https://psinv.net/api/sendemail.php";

export const sendEmail = async ({
  firstName,
  lastName,
  mobile,
  whatsapp,
  email,
}) => {
  try {
    const htmlBody = `
      <table align="center" width="700" cellpadding="0" cellspacing="0" border="0" style="font-family: Arial, sans-serif; background-color: #ffffff; border: 1px solid #e2e2e2; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.05); margin: auto;">
        <tr>
          <td style="padding: 25px 30px;">
            <h2 style="color: #E35F27; font-size: 22px; margin-bottom: 20px;">
              📄 New Registration Submitted
            </h2>

            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color: #f9f9f9; padding: 15px 20px; border-radius: 8px;">
              <tr>
                <td style="padding: 10px 0;"><strong>👤 First Name:</strong> ${firstName}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0;"><strong>👤 Last Name:</strong> ${lastName}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0;"><strong>📞 Mobile Number:</strong> ${mobile}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0;"><strong>📱 WhatsApp Number:</strong> ${whatsapp}</td>
              </tr>
              <tr>
                <td style="padding: 10px 0;"><strong>✉️ Email:</strong> ${email}</td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td style="text-align: center; padding: 15px 10px; background-color: #f1f1f1; font-size: 12px; color: #888;">
            This email was generated by the PSI Vision download portal.
          </td>
        </tr>
      </table>
    `;

    const payload = {
      body: htmlBody,
      receiver: "jamil.i@psinv.net, farah.achi@psinv.net, abdelrahman.gamal@psinv.net",
      subject: `🧾 New PSI Vision Form Submission | ${firstName} ${lastName}`,
      filename: "",
      filedata: "",
    };

    const response = await fetch("https://psinv.net/api/sendemail.php", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

const result = await response.json();
console.log("Email API Response:", result);


if (!response.ok || !result.message?.toLowerCase().includes("success")) {
  throw new Error(result.message || "Email failed");
}


    return result;
  } catch (error) {
    console.error("Email sending failed:", error);
    throw error;
  }
};
